// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPQjF0iuF0PV4lj4RmxyE_k9kZQkcU5kY',
    appId: '1:902743827168:web:ca5e2168f0a5c03677a685',
    messagingSenderId: '902743827168',
    projectId: 'skin-type-app',
    authDomain: 'skin-type-app.firebaseapp.com',
    storageBucket: 'skin-type-app.firebasestorage.app',
    measurementId: 'G-8XJD1J7049',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpUpOwg-zlpJy7wcbrat-qSPf1J9vgWVI',
    appId: '1:902743827168:android:a0703445b666175f77a685',
    messagingSenderId: '902743827168',
    projectId: 'skin-type-app',
    storageBucket: 'skin-type-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1wZ_EABDKo4Ay2TnzU32ICCZk8Jr08z0',
    appId: '1:902743827168:ios:db9f32338160fa4d77a685',
    messagingSenderId: '902743827168',
    projectId: 'skin-type-app',
    storageBucket: 'skin-type-app.firebasestorage.app',
    iosBundleId: 'com.example.skinTypeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAPQjF0iuF0PV4lj4RmxyE_k9kZQkcU5kY',
    appId: '1:902743827168:web:04d0d94c24c905d777a685',
    messagingSenderId: '902743827168',
    projectId: 'skin-type-app',
    authDomain: 'skin-type-app.firebaseapp.com',
    storageBucket: 'skin-type-app.firebasestorage.app',
    measurementId: 'G-DRM7174XR2',
  );
}
